name="R e y h a n e h "
print(name)
print(name[0])
print(name[0:2])
print(name.upper())
print(name.lower())
print(name.strip())
print(name.replace("h","R"))
print(name.replace(" ",""))
print(name.replace(""," "))
print(name.lower().strip().replace(""," "))
print(len(name)/2)
print(len(name.strip().replace(" ",""))/2)